route/v1/docker.go
When creating an app, the portMap field can be left empty or set to 0, but when updating an error gets thrown
=> fix: prevent strconv.Atoi error on update app's settings

common/message.go, go.mod, go.sum, route/v1/docker.go, service/docker.go
=> include additional app properties in the `notify.Application` struct sent to the frontend via socket.io

route/v1/appstore.go, route/v1/docker.go, service/docker.go
=> update protocol comparision to be case insensitive

service/docker.go
=> use `Accept: application/html` in the request header when checking container health

common/constants.go, model/app.go, model/manifest.go, service/docker.go
=> include `appstore_id` in my app list for app cloning

pkg/docker/digest.go
port from https://github.com/containrrr/watchtower/pull/1533
=> add oci image index support

route/v1/docker.go
=> fix missing app StoreID when getting app details

service/docker.go
=> add `docker:image:updated` property to `app:update-end` event

cmd/appfile2compose/appfile.go, service/docker.go
=> fix image pull progress in app update process

build/scripts/setup/script.d/06-setup-app-management.sh, build/sysroot/usr/share/casaos/cleanup/script.d/06-cleanup-app-management.sh
=> fix installation issue for Mint Linux

route/v1/docker.go, route/v2/docker.go, route/v2/image.go, service/docker.go, service/v1/app.go
=> fix missing app:name in pull image progress

go.mod, pkg/docker/digest.go, pkg/docker/digest_test.go, service/v1/appstore.go
=> fix architecture detection for `application/vnd.oci.image.index.v1+json` image manifest

service/container.go
=> :bug: fix IceWhaleTech/CasaOS#892

service/compose_app.go
fix change title is worry. build Update Event Properties from new compose app.
=> fix: change title response is worry

service/compose_app.go
the bug will happened in merging two disks.
It will stop app and merge and start. 
But the merge is too fast. So when It start a app. the stop didn't complete yet.
=> fix: to check container state and wait some time before start a container

build/sysroot/etc/casaos/app-management.conf.sample, build/sysroot/etc/casaos/env, main.go, pkg/config/config.go, pkg/config/init.go, route/v2.go, route/v2/global.go, service/appstore_management.go, service/compose_app.go, service/compose_service.go
the PR allows the user to set any global env to app by Casaos-CLI
like
```
casaos-cli app-management set global OPENAI_API_KEY sk-xxxxxxxx
casaos-cli app-management set global ADMIN_PASS password
casaos-cli app-management set global ANYNAME anyvalue
```
=> feat: to config any environment by casaos-CLI

service/compose_app.go
=> fix: didn't interpolate APPID

route/v2/compose_app.go, service/utils.go
same the title
relate: https://github.com/IceWhaleTech/CasaOS/issues/993
=> fix: only have $ when save in setting panel

go.mod, go.sum
close https://github.com/IceWhaleTech/CasaOS/issues/1332
=> fix: fix can't install app in only ipv4 machine

.github/workflows/release.yml
Reverts IceWhaleTech/CasaOS-AppManagement#145
=> Revert "chore: bump golang to 1.21"

.github/workflows/release.yml
Reverts IceWhaleTech/CasaOS-AppManagement#146
=> Revert "Revert "chore: bump golang to 1.21""

.goreleaser.debug.yaml, .goreleaser.yaml, build/scripts/migration/script.d/06-migrate-app-management.sh
It depends upon https://github.com/IceWhaleTech/github/pull/3
resolved https://github.com/IceWhaleTech/CasaOS/issues/1669
=> Add initial RISC-V support
